name: ci
on:
  push:
  pull_request:

jobs:
  scenarios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test
      - if: failure()
        run: docker compose logs
